# SPDX-FileCopyrightText: 2024 Hannes Bohring <hannes.bohring@ufz.de>
# SPDX-FileCopyrightText: 2024 Helmholtz Centre for Environmental Research GmbH - UFZ
#
# SPDX-License-Identifier: EUPL-1.2

sms:

  sms-backend:
    enabled: true

    nginx:
      image:
        tag: "ufz-backend-1.23.1"

    backend:
      image:
        tag: "ufz-prod-1.23.1"

  sms-frontend:
    enabled: true
    image:
      repository: "registry.hzdr.de/hub-terra/sms/orchestration/generic-frontend"
      tag: "1.23.1"
    nginxConfig: |
      server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        root /usr/share/nginx/html/;

        location /sms {
            alias /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
      }

  sms-idl:
    enabled: true
    image:
      repository: "registry.hzdr.de/hub-terra/sms/gfz-idl/backend"
      tag: "0.5.0"

  sms-cv:
    enabled: true
    cv:
      enabled: true
      image:
        registry: "registry.hzdr.de"
        image: "hub-terra/sms/sms-cv"
        tag: "1.3.3"
      environmentVariables:
        - name: "DEBUG"
          value: "false"
        - name: CV_BASE_URL
          value: "sms/cv/"
        - name: CORS_ALLOW_ALL_ORIGINS
          value: "true"
        - name: CSRF_TRUSTED_ORIGINS
          value: "https://sms-cv.helmholtz.cloud"
        - name: STATIC_URL
          value: 'sms/cv/static/'
        - name: SQL_HOST
          value: 'postgres.intranet.ufz.de'
        - name: SQL_DATABASE
          value: 'sms_cv_prod'
        - name: SQL_USER
          value: 'sms_cv_prod_adm'
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: custom-rdm-sms-cv
              key: SQL_PASSWORD
        - name: CV_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: custom-rdm-sms-cv
              key: SECRET_KEY
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              name: custom-rdm-sms-cv
              key: GITLAB_TOKEN
    cvbackup:
      enabled: false

    imagePullSecrets:
      - name: custom-rdm-sms.docker-registry

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/issuer: "letsencrypt-production"
        cert-manager.io/private-key-algorithm: "ECDSA"
        cert-manager.io/private-key-size: "384"
        cert-manager.io/private-key-rotation-policy: "Always"
        nginx.ingress.kubernetes.io/enable-cors: "false"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          add_header 'X-Content-Type-Options' 'nosniff' always;
          add_header 'Content-Security-Policy' "default-src 'self'; script-src 'self' 'unsafe-inline'; img-src * data: ; style-src 'self' 'unsafe-inline' * ; font-src 'self' *; frame-src 'self' *.ufz.de ; child-src 'self' *.ufz.de ; object-src 'none' ; frame-ancestors 'self' http://*.ufz.de https://*.ufz.de ;connect-src https://*.ufz.de ;" always;
          add_header 'X-XSS-Protection' '1';
        nginx.ingress.kubernetes.io/app-root: /sms/cv
      hosts:
        - host: "sms-cv.helmholtz.cloud"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: "sms-cv-helmholtz-cloud-tls"
          hosts:
            - "sms-cv.helmholtz.cloud"

# dont deploy local backend DBs (central Postgres is used)

  sms-cv-db:
    enabled: false

  sms-backend-db:
    enabled: false
