# SPDX-FileCopyrightText: 2020 - 2024
# - Martin Abbrent <martin.abbrent@ufz.de>
# - Tobias Kuhnert <tobias.kuhnert@ufz.de>
# - Helmholtz Centre for Environmental Research GmbH - UFZ (UFZ, https://www.ufz.de)
#
# SPDX-License-Identifier: EUPL-1.2
version: '3.7'
services:

  node:
    build:
      context: '.'
      dockerfile: 'docker/local-dev/Dockerfile-local-dev'
    user: "node"
    working_dir: /home/node/
    ports:
      - 3000:3000
    environment:
      BASE_URL: "/"
      INSTITUTE: "ufz"
      SMS_BACKEND_URL: "http://localhost:5000/rdm/svm-api/v1"
      CV_BACKEND_URL: "http://localhost:8000/api/v1"
      NUXT_ENV_PID_BASE_URL: "https://hdl.handle.net"
      NUXT_ENV_CLIENT_ID: "rdmsms-pkce-flow"
      NUXT_ENV_OIDC_WELL_KNOWN: "https://webapp-stage.intranet.ufz.de/idp/oidc/v1/.well-known/openid-configuration"
      NUXT_ENV_SCOPE: "openid profile email offline_access"
      NUXT_ENV_OIDC_SCHEME: "true"
      NUXT_ENV_OIDC_RESPONSE_TYPE: "code"
      NUXT_ENV_OIDC_GRANT_TYPE: "authorization_code"
      NUXT_ENV_OIDC_CHALLANGE: "S256"
    volumes:
      - .:/home/node/
    command: >
      bash -c "npm install
      && npm run dev"
