"""Add {groups_ids, is_private, is_superuser} attributes

Revision ID: 523e1f0740ed
Revises: 3abc641a1fdb
Create Date: 2021-09-22 07:19:02.889043

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '523e1f0740ed'
down_revision = '3abc641a1fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('groups_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('configuration', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('device', sa.Column('groups_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('device', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('platform', sa.Column('groups_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('platform', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    op.drop_column('platform', 'is_private')
    op.drop_column('platform', 'groups_ids')
    op.drop_column('device', 'is_private')
    op.drop_column('device', 'groups_ids')
    op.drop_column('configuration', 'is_private')
    op.drop_column('configuration', 'groups_ids')
    # ### end Alembic commands ###
