"""Add contact roles

Revision ID: 88f15687e6b9
Revises: 0139893c4e15
Create Date: 2022-01-11 11:02:36.738628

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '88f15687e6b9'
down_revision = '0139893c4e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('uri', sa.String(length=256), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('contact_role',
                    sa.Column('contact_id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.PrimaryKeyConstraint('contact_id', 'role_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_role')
    op.drop_table('role')
    # ### end Alembic commands ###
