"""Add AuditMixin to custom_field

Revision ID: 92011f3037b0
Revises: 13e35f226a7c
Create Date: 2021-12-16 16:55:55.171827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92011f3037b0'
down_revision = '13e35f226a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('custom_field', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('custom_field', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('custom_field', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_CustomField_updated_by_id', 'custom_field', 'user', ['updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_CustomField_created_by_id', 'custom_field', 'user', ['created_by_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_CustomField_created_by_id', 'custom_field', type_='foreignkey')
    op.drop_constraint('fk_CustomField_updated_by_id', 'custom_field', type_='foreignkey')
    op.drop_column('custom_field', 'updated_by_id')
    op.drop_column('custom_field', 'created_by_id')
    op.drop_column('custom_field', 'updated_at')
    op.drop_column('custom_field', 'created_at')
    # ### end Alembic commands ###
