"""empty message

Revision ID: b8d2bacb58c3
Revises: ddabda846db9
Create Date: 2020-11-13 13:46:17.025150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d2bacb58c3'
down_revision = 'ddabda846db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
