"""empty message

Revision ID: d5148bc31abd
Revises: a34dbc35eb6b
Create Date: 2022-10-17 07:30:21.074829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5148bc31abd'
down_revision = '35881b2a27d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_attachment', sa.Column('internal_url', sa.String(length=1024), nullable=True))
    op.add_column('platform_attachment', sa.Column('internal_url', sa.String(length=1024), nullable=True))
    op.add_column('configuration_attachment', sa.Column('internal_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_attachment', 'internal_url')
    op.drop_column('platform_attachment', 'internal_url')
    op.drop_column('configuration_attachment', 'internal_url')
    # ### end Alembic commands ###
