"""empty message

Revision ID: ddabda846db9
Revises: 368d66492de5
Create Date: 2020-11-13 13:42:28.041091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddabda846db9'
down_revision = '368d66492de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('status', sa.String(length=256), nullable=True))
    op.add_column('device_property', sa.Column('resolution', sa.Float(), nullable=True))
    op.add_column('device_property', sa.Column('resolutionUnitName', sa.String(length=256), nullable=True))
    op.add_column('device_property', sa.Column('resolution_unit_uri', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_property', 'resolution_unit_uri')
    op.drop_column('device_property', 'resolutionUnitName')
    op.drop_column('device_property', 'resolution')
    op.drop_column('configuration', 'status')
    # ### end Alembic commands ###
