# SPDX-FileCopyrightText: 2020
# - Nils Brinckmann <nils.brinckmann@gfz-potsdam.de>
# - Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences (GFZ, https://www.gfz-potsdam.de)
#
# SPDX-License-Identifier: HEESIL-1.0

"""empty message

Revision ID: eac266534186
Revises: 73841fae7c1b
Create Date: 2020-12-15 09:21:23.754677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eac266534186"
down_revision = "73841fae7c1b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configuration_device",
        sa.Column("firmware_version", sa.String(length=256), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("configuration_device", "firmware_version")
    # ### end Alembic commands ###
