# Web client of the Sensor Management System software developed within
# the Helmholtz DataHub Initiative by GFZ and UFZ.
# 
# Copyright (C) 2020
# - Martin Abbrent (UFZ, martin.abbrent@ufz.de)
# - Helmholtz Centre for Environmental Research GmbH - UFZ 
#   (UFZ, https://www.ufz.de)
# 
# Parts of this program were developed within the context of the
# following publicly funded projects or measures:
# - Helmholtz Earth and Environment DataHub
#   (https://www.helmholtz.de/en/research/earth_and_environment/initiatives/#h51095)
# 
# Licensed under the HEESIL, Version 1.0 or - as soon they will be 
# approved by the "Community" - subsequent versions of the HEESIL 
# (the "Licence").
# 
# You may not use this work except in compliance with the Licence.
# 
# You may obtain a copy of the Licence at: 
# https://gitext.gfz-potsdam.de/software/heesil
# 
# Unless required by applicable law or agreed to in writing, software 
# distributed under the Licence is distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or 
# implied. See the Licence for the specific language governing 
# permissions and limitations under the Licence.
stages:
  - check
  - test
  - build-ufz
  - deploy-ufz

cache:
  paths:
    - dist

check-lint-ufz:
  stage: check
  image: node:10.16.3-stretch
  before_script:
    - node -v
    - npm install
  script:
    - npm run lint
  allow_failure: true
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules

test-frontend-unit-tests-ufz:
  stage: test
  image: node:10.16.3-stretch
  before_script:
    - node -v
    - npm install
  script:
    - npm test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules


build_app:
  stage: build-ufz
  variables:
    BASE_URL: "/rdm/svm"
    SMS_BACKEND_URL: "https://webapp-stage.intranet.ufz.de/rdm/svm-api/v1"
    CV_BACKEND_URL: "http://rdm-test.intranet.ufz.de:5000/api"
    NUXT_ENV_REDIRECT_URI: "https://webapp-stage.intranet.ufz.de/rdm/svm/login-callback"
    NUXT_ENV_CLIENT_ID: "rdmsvm-implicit-flow"
    NUXT_ENV_AUTHORITY: "https://webapp.ufz.de/idp/oidc/v1"
    NUXT_ENV_RESPONSE_TYPE: "id_token"
    NUXT_ENV_SCOPE: "openid profile email"
    NUXT_ENV_POST_LOGOUT_REDIRECT_URI: "https://webapp-stage.intranet.ufz.de/rdm/svm/logout-callback"
    NUXT_ENV_SILENT_REDIRECT_URI: "https://webapp-stage.intranet.ufz.de/rdm/svm/silent-callback"
    NUXT_ENV_FILTER_PROTOCOL_CLAIMS: 'false'
    NUXT_ENV_AUTOMATIC_SILENT_RENEW: 'true'
    NUXT_ENV_SILENT_RENEW_INTERVAL:  6900000 # 115 minutes in milliseconds
    NUXT_ENV_LOAD_USER_INFO: 'true'
  image: node:latest
  script:
    - npm install
    - npm run build


build_image:
  stage: deploy-ufz
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/deployment/ufz/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE --build-arg BUILD_DATE=$(date --utc +%FT%TZ) --build-arg VCS_REF=$CI_COMMIT_SHA

