stages:
  - check
  - test
  - build-ufz
  - deploy-ufz

cache:
  paths:
    - dist

check-lint-ufz:
  stage: check
  image: node:10.16.3-stretch
  before_script:
    - node -v
    - npm install
  script:
    - npm run lint
  allow_failure: true
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules

test-frontend-unit-tests-ufz:
  stage: test
  image: node:10.16.3-stretch
  before_script:
    - node -v
    - npm install
  script:
    - npm test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules


build_app:
  stage: build-ufz
  image: node:latest
  script:
    - npm install
    - npm run generate


build_image:
  stage: deploy-ufz
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/deployment/ufz/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE --build-arg BUILD_DATE=$(date --utc +%FT%TZ) --build-arg VCS_REF=$CI_COMMIT_SHA

