version: '3.4'

services:
  app:
    container_name: app
    build:
      context: app/
      dockerfile: Dockerfile-dev
    volumes:
      - './app:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig