version: '3.4'

services:
  app:
    container_name: app
    build:
      context: app/
      dockerfile: Dockerfile-dev
    volumes:
      - './app:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/users_test
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    build:
      context: ./app/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres