## SPDX-FileCopyrightText: 2026 Hannes Bohring <hannes.bohring@ufz.de>
## SPDX-FileCopyrightText: 2026 Helmholtz Centre for Environmental Research GmbH - UFZ
##
## SPDX-License-Identifier: EUPL-1.2

apiVersion: v2
name: sms-stage
description: Umbrella-Chart for SMS-Stage
version: 0.4.0-alpha0

dependencies:
- name: sms
  alias: "sms"
  version: "0.4.0-alpha0"

  # Devel-Channel
  repository: "https://codebase.helmholtz.cloud/api/v4/projects/7722/packages/helm/devel"

  # Stable-Channel
#  repository: "https://codebase.helmholtz.cloud/api/v4/projects/7722/packages/helm/stable"
