# SPDX-FileCopyrightText: 2023 Norman Ziegner <norman.ziegner@ufz.de>
# SPDX-FileCopyrightText: 2023 Helmholtz Centre for Environmental Research GmbH - UFZ
#
# SPDX-License-Identifier: EUPL-1.2
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
  namespace: sms-cv-testing
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sms-administration@ufz.de
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx
