# SPDX-FileCopyrightText: 2026
# - Nils Brinckmann <nils.brinckmann@gfz.de>
# - GFZ - Helmholtz Centre for Geosciences (GFZ, https://www.gfz.de)
#
# SPDX-License-Identifier: EUPL-1.2

"""Openapi spec for the generator views."""

paths = {
    "/controller/generators/serial-number": {
        "get": {
            "tags": ["Controller"],
            "parameters": [
                {
                    "in": "query",
                    "name": "seed",
                    "schema": {
                        "type": "integer",
                    },
                    "required": False,
                    "description": "Seed for the random choices.",
                },
                {
                    "in": "query",
                    "name": "organization_part",
                    "schema": {
                        "type": "string",
                    },
                    "required": False,
                    "description": "".join(
                        [
                            "Organization part of the generated serial number. ",
                            "This is used like GFZ in GFZ-AB-1234",
                        ]
                    ),
                },
            ],
            "responses": {
                "200": {
                    "content": {
                        "application/vnd.api+json": {
                            "schema": {"properties": {"data": {"type": "string"}}}
                        }
                    },
                    "description": "A serial number generated by the system",
                }
            },
            "description": "".join(
                [
                    "Generate a serial number by the system that can be used ",
                    "if the manufacturer doesn't provide one.",
                ]
            ),
            "operationId": "controller_generators_serial_number",
        }
    }
}
