FROM python:3.6.4 as build

ARG BUILD_DATE
ARG VCS_REF

LABEL maintainer="Kotyba Alhaj Taha <kotyba.alhaj-taha@ufz.de>" \
    org.opencontainers.image.title="SVM Image" \
    org.opencontainers.image.authors="Kotyba Alhaj Taha <kotyba.alhaj-taha@ufz.de>"  \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.version="0.1" \
    org.opencontainers.image.url="#" \
    org.opencontainers.image.revision=$VCS_REF \
    org.opencontainers.image.created=$BUILD_DATE


# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install --upgrade pip\
   && pip install -r requirements.txt

# add app
#COPY app /usr/src/app


FROM build

EXPOSE 5000

#run server
#CMD ['python', 'manage.py', 'run', '-h', '0.0.0.0']
CMD python manage.py run -h 0.0.0.0