# SPDX-FileCopyrightText: 2021 - 2024
# - Nils Brinckmann <nils.brinckmann@gfz-potsdam.de>
# - Marc Hanisch <marc.hanisch@gfz-potsdam.de>
# - Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences (GFZ, https://www.gfz-potsdam.de)
#
# SPDX-License-Identifier: EUPL-1.2

version : '3.3'

services:
  nginx:
    image: registry.hzdr.de/hub-terra/sms/orchestration/nginx:gfz-sandbox-latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`${SMS_SANDBOX_FQDN}`) && PathPrefix(`${SMS_SANDBOX_BASE_URL:-/}`)"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.routers.nginx.tls.certresolver=sectigo"
    volumes:
      - backend-static-files:/usr/share/nginx/html/static/backend:ro
      - idl-static-files:/usr/share/nginx/html/static/idl:ro
    networks:
      - nginx
      - traefik

  idl:
    image: registry.hzdr.de/hub-terra/sms/gfz-idl/backend:0.4.2
    restart: unless-stopped
    environment:
      DJANGO_DEBUG: 'false'
      DJANGO_ALLOWED_HOSTS: 'localhost idl sensors-sandbox.gfz-potsdam.de'
      DJANGO_BASE_PATH: idl/
      DJANGO_STATIC_URL: /static/idl/
      DJANGO_STATIC_ROOT: /static/idl/
      DJANGO_DB_ENGINE: django.db.backends.postgresql
      DJANGO_DB_NAME: idl
      DJANGO_DB_USER: $SMS_SANDBOX_IDL_DB_USER
      DJANGO_DB_PASSWORD: $SMS_SANDBOX_IDL_DB_PASSWORD
      DJANGO_DB_HOST: idl-db
      DJANGO_DB_PORT: 5432
      DJANGO_SECRET_KEY: ${SMS_SANDBOX_IDL_SECRET_KEY}
      DJANGO_CSRF_TRUSTED_ORIGINS: 'https://sensors-sandbox.gfz-potsdam.de'
      IDL_TOKEN: $SMS_SANDBOX_IDL_TOKEN
      OIDC_WELL_KNOWN_URL: https://login.helmholtz.de/oauth2/.well-known/openid-configuration
      VO_ADMIN_CONVENTIONS: '*:gfz-sms-admin,*:ufz-sms-admin,*:kit-sms-admin,*:fzj-sms-admin'
      VO_MEMBER_CONVENTIONS: 'gfz:*,*:gfz-sms-member,*:ufz-sms-member,*:kit-sms-member,*:fzj-sms-member'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idl.rule=Host(`${SMS_SANDBOX_FQDN}`) && PathPrefix(`${SMS_SANDBOX_BASE_URL:-/}idl/`)"
      - "traefik.http.routers.idl.entrypoints=https"
      - "traefik.http.routers.idl.tls.certresolver=sectigo"
      - "traefik.http.services.idl.loadbalancer.server.port=8000"
    volumes:
      - idl-static-files:/static/idl
    networks:
      - nginx
      - idl-db
      - traefik

  idl-db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $SMS_SANDBOX_IDL_DB_PASSWORD
      POSTGRES_USER: $SMS_SANDBOX_IDL_DB_USER
      POSTGRES_DB: idl
    volumes:
      - "idl-db-data:/var/lib/postgresql/data"
    shm_size: 128M
    networks:
      - idl-db

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - backend

  minio:
    image: minio/minio:RELEASE.2021-07-12T02-44-53Z
    restart: unless-stopped
    volumes:
      - minio-data:/data/minio
    networks:
      - nginx
      - backend
      - traefik
    environment:
      MINIO_ROOT_USER: ${SMS_SANDBOX_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${SMS_SANDBOX_MINIO_ROOT_PASSWORD}
    #      To deactivate the console
    #      MINIO_BROWSER: "off"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`${SMS_SANDBOX_FQDN}`) && PathPrefix(`${SMS_SANDBOX_BASE_URL:-/}sms-attachments/`)"
      - "traefik.http.routers.minio.entrypoints=https"
      - "traefik.http.routers.minio.tls.certresolver=sectigo"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
    command: server /data/minio --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  mc:
    image: registry.hzdr.de/hub-terra/sms/orchestration/mc:gfz-sandbox-latest
    environment:
      MINIO_ROOT_USER: ${SMS_SANDBOX_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${SMS_SANDBOX_MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${SMS_SANDBOX_MINIO_BUCKET_NAME}
    depends_on:
      - minio
    networks:
      - backend
    entrypoint: ['/create_bucket.sh']

  backend-db:
    image: postgis/postgis:12-3.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $SMS_SANDBOX_BACKEND_DB_PASSWORD
      POSTGRES_USER: $SMS_SANDBOX_BACKEND_DB_USER
      POSTGRES_DB: backend
    volumes:
      - "backend-db-data:/var/lib/postgresql/data"
    shm_size: 128M
    networks:
      - backend

  backend:
    image: registry.hzdr.de/hub-terra/sms/orchestration/backend:gfz-sandbox-latest
    restart: unless-stopped
    environment:
      URL_PREFIX: /backend/api/v1
      STATIC_URL: /static/backend
      APP_SETTINGS: project.config.ProductionConfig
      DATABASE_URL: postgresql://${SMS_SANDBOX_BACKEND_DB_USER}:${SMS_SANDBOX_BACKEND_DB_PASSWORD}@backend-db:5432/backend
      OIDC_USERNAME_CLAIM: eduperson_principal_name
      WELL_KNOWN_URL: https://login.helmholtz.de/oauth2/.well-known/openid-configuration
      MINIO_ACCESS_KEY: ${SMS_SANDBOX_MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${SMS_SANDBOX_MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${SMS_SANDBOX_MINIO_BUCKET_NAME}
      MINIO_ENDPOINT: minio:9000
      DOWNLOAD_ENDPOINT: https://sensors-sandbox.gfz-potsdam.de
      SECRET_KEY: ${SMS_SANDBOX_BACKEND_SECRET_KEY}
      ALLOWED_MIME_TYPES: ${SMS_SANDBOX_ALLOWED_MIME_TYPES}
      ELASTICSEARCH_URL: http://elastic-search:9200
      HTTP_ORIGINS: ${SMS_SANDBOX_HTTP_ORIGINS}
      SMS_IDL_TOKEN: ${SMS_SANDBOX_IDL_TOKEN}
      IDL_URL: http://idl:8000/idl/api/idl
      CV_URL: https://sms-cv.helmholtz.cloud/sms/cv/api/v1
      SMS_BACKEND_URL: /backend/api/v1
      PKCE_CLIENT_ID: ${SMS_SANDBOX_PKCE_CLIENT_ID}
      PKCE_SCOPES: profile openid email eduperson_principal_name
      INSTITUTE: gfz
      SMS_FRONTEND_URL: https://sensors-sandbox.gfz-potsdam.de
      B2INST_TOKEN: ${SMS_SANDBOX_B2INST_TOKEN}
      B2INST_URL: https://b2inst-test.gwdg.de
      B2INST_COMMUNITY: DataHub-Helmholtz-RF-EE
      PID_SERVICE_URL: https://rz-vm561.gfz-potsdam.de:8000/api/handles
      PID_SERVICE_USER: ${PID_SERVICE_USER}
      PID_SERVICE_PASSWORD: ${PID_SERVICE_PASSWORD}
      PID_PREFIX: 20.500.14372
      PID_SUFFIX: SMS-Sandbox
      TSM_ENDPOINTS: '[{"fields": {"name": "GFZ", "url": "https://timeseries.gfz-potsdam.de/tsmdl/api/v1"}, "model": "TsmEndpoint", "pk": 1}]'
      EXPORT_CONTROL_VO_LIST: urn:geant:helmholtz.de:gfz:group:sensor-management-system-export-control#idp.gfz-potsdam.de
      # We only want to allow access to external resources via the proxy - not to internal ones
      PROXY_NETLOC_BLOCKLIST: 127.0.0.1,localhost,backend-db,backend,minio,elastic-search,idl-db,idl,nginx,traefik
    depends_on:
      - backend-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${SMS_SANDBOX_FQDN}`) && PathPrefix(`${SMS_SANDBOX_BASE_URL:-/}backend/`)"
      - "traefik.http.routers.backend.entrypoints=https"
      - "traefik.http.routers.backend.tls.certresolver=sectigo"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
    volumes:
      - backend-static-files:/usr/src/app/project/static
    networks:
      - backend
      - nginx
      - traefik

volumes:
  idl-db-data:
  idl-static-files:
  elasticsearch-data:
  minio-data:
  backend-db-data:
  backend-static-files:
networks:
  nginx:
  traefik:
    external: true
  backend:
  idl-db:

