# SPDX-FileCopyrightText: 2021
# - Kotyba Alhaj Taha <kotyba.alhaj-taha@ufz.de>
# - Helmholtz Centre for Environmental Research GmbH - UFZ (UFZ, https://www.ufz.de)
#
# SPDX-License-Identifier: HEESIL-1.0

"""Add active attribute to user table.

Revision ID: 0028782b3d04
Revises: 3abc641a1fdb
Create Date: 2021-09-16 08:35:56.991907

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0028782b3d04"
down_revision = "3abc641a1fdb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "active")
    # ### end Alembic commands ###
