# SPDX-FileCopyrightText: 2026
# - Nils Brinckmann <nils.brinckmann@gfz.de>
# - GFZ - Helmholtz Centre for Geosciences (GFZ, https://www.gfz.de)
#
# SPDX-License-Identifier: EUPL-1.2

"""Add a table for the organizations.

Revision ID: 13125b74ad86
Revises: 452c3ea4532e
Create Date: 2026-07-02 07:18:16.374977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13125b74ad86"
down_revision = "452c3ea4532e"
branch_labels = None
depends_on = None


def upgrade():
    """Add the organization table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("ror", sa.String(length=256), nullable=True),
        sa.Column("abbreviation", sa.String(length=8), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###
    connection = op.get_bind()

    select_query = """
    select distinct organization
    from contact
    where organization is not null
    and organization <> ''
    """

    organization_names = []
    for res in connection.execute(sa.text(select_query)).fetchall():
        organization_names.append(res["organization"])

    insert_query = """
    insert into organization (name) values (:name)
    """

    for organization_name in organization_names:
        connection.execute(
            sa.text(insert_query), {"name": organization_name})


def downgrade():
    """Remove the organization table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization")
    # ### end Alembic commands ###
