# SPDX-FileCopyrightText: 2026
# - Nils Brinckmann <nils.brinckmann@gfz.de>
# - GFZ - Helmholtz Centre for Geosciences (GFZ, https://www.gfz.de)
#
# SPDX-License-Identifier: EUPL-1.2

"""Add more fields for contacts to fill out all the sensorML fields.

Revision ID: 1742a81aaf19
Revises: 13125b74ad86
Create Date: 2026-07-23 05:51:31.864588

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1742a81aaf19"
down_revision = "13125b74ad86"
branch_labels = None
depends_on = None


def upgrade():
    """Add additional fields to the contacts table."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contact", schema=None) as batch_op:
        batch_op.add_column(sa.Column("telephone", sa.String(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("fax_number", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(sa.Column("street", sa.String(length=256), nullable=True))
        batch_op.add_column(
            sa.Column("street_number", sa.String(length=256), nullable=True)
        )
        batch_op.add_column(sa.Column("city", sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column("zip_code", sa.String(length=256), nullable=True))
        batch_op.add_column(
            sa.Column("administrative_area", sa.String(length=256), nullable=True)
        )
        batch_op.add_column(sa.Column("country", sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column("building", sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column("room", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Remove additional fields from the contacts table."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contact", schema=None) as batch_op:
        batch_op.drop_column("room")
        batch_op.drop_column("building")
        batch_op.drop_column("country")
        batch_op.drop_column("administrative_area")
        batch_op.drop_column("zip_code")
        batch_op.drop_column("city")
        batch_op.drop_column("street_number")
        batch_op.drop_column("street")
        batch_op.drop_column("fax_number")
        batch_op.drop_column("telephone")
    # ### end Alembic commands ###
