# SPDX-FileCopyrightText: 2026
# - Nils Brinckmann <nils.brinckmann@gfz.de>
# - GFZ - Helmholtz Centre for Geosciences (GFZ, https://www.gfz.de)
#
# SPDX-License-Identifier: EUPL-1.2

"""Add the flag column for the system generated serial number.

Revision ID: 452c3ea4532e
Revises: 3583b07a3c98
Create Date: 2026-06-30 10:41:02.281602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "452c3ea4532e"
down_revision = "3583b07a3c98"
branch_labels = None
depends_on = None


def upgrade():
    """Execute the tasks for the structural change and update the values for existing entries."""
    with op.batch_alter_table("device", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("has_system_generated_serial_number", sa.Boolean(), nullable=True)
        )
    with op.batch_alter_table("platform", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("has_system_generated_serial_number", sa.Boolean(), nullable=True)
        )

    connection = op.get_bind()

    for table in ["device", "platform"]:
        update_query = f"update {table} set has_system_generated_serial_number = false where has_system_generated_serial_number is null"
        connection.execute(update_query)


def downgrade():
    """Undo the structural changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("platform", schema=None) as batch_op:
        batch_op.drop_column("has_system_generated_serial_number")
    with op.batch_alter_table("device", schema=None) as batch_op:
        batch_op.drop_column("has_system_generated_serial_number")
    # ### end Alembic commands ###
