# SPDX-FileCopyrightText: 2022
# - Nils Brinckmann <nils.brinckmann@gfz-potsdam.de>
# - Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences (GFZ, https://www.gfz-potsdam.de)
#
# SPDX-License-Identifier: HEESIL-1.0

"""empty message

Revision ID: 6a6436214ad3
Revises: bd8c63810159
Create Date: 2022-10-28 08:54:17.457487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6a6436214ad3"
down_revision = "bd8c63810159"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("configuration", sa.Column("site_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "configuration", "site", ["site_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "configuration", type_="foreignkey")
    op.drop_column("configuration", "site_id")
    # ### end Alembic commands ###
