# SPDX-FileCopyrightText: 2026
# - Nils Brinckmann <nils.brinckmann@gfz.de>
# - GFZ - Helmholtz Centre for Geosciences (GFZ, https://www.gfz.de)
#
# SPDX-License-Identifier: EUPL-1.2

"""Add administrative_area to the sites.

Revision ID: 6dd344b64fa2
Revises: 1742a81aaf19
Create Date: 2026-07-28 12:41:02.869568

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6dd344b64fa2"
down_revision = "1742a81aaf19"
branch_labels = None
depends_on = None


def upgrade():
    """Do the structural changes on the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("administrative_area", sa.String(length=256), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    """Undo the structural changes on the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.drop_column("administrative_area")
    # ### end Alembic commands ###
