# SPDX-FileCopyrightText: 2020
# - Kotyba Alhaj Taha <kotyba.alhaj-taha@ufz.de>
# - Helmholtz Centre for Environmental Research GmbH - UFZ (UFZ, https://www.ufz.de)
#
# SPDX-License-Identifier: EUPL-1.2

"""empty message

Revision ID: 73841fae7c1b
Revises: 7304bdad35dc
Create Date: 2020-11-16 13:55:56.866801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73841fae7c1b"
down_revision = "7304bdad35dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("device_property", sa.Column("resolution", sa.Float(), nullable=True))
    op.add_column(
        "device_property",
        sa.Column("resolution_unit_name", sa.String(length=256), nullable=True),
    )
    op.add_column(
        "device_property",
        sa.Column("resolution_unit_uri", sa.String(length=256), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("device_property", "resolution_unit_uri")
    op.drop_column("device_property", "resolution_unit_name")
    op.drop_column("device_property", "resolution")
    # ### end Alembic commands ###
