# SPDX-FileCopyrightText: 2026
# - Nils Brinckmann <nils.brinckmann@gfz-potsdam.de>
# - Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences (GFZ, https://www.gfz-potsdam.de)
# - Helmholtz Centre for Environmental Research GmbH - UFZ (UFZ, https://www.ufz.de)
#
# SPDX-License-Identifier: EUPL-1.2
"""Add a column to indicate if a parameter is calibration relevant.

Revision ID: 9aa14bd36aca
Revises: 79cf3f3124ea
Create Date: 2026-02-06 11:46:47.111680

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9aa14bd36aca"
down_revision = "79cf3f3124ea"
branch_labels = None
depends_on = None


def upgrade():
    """Do the database structure change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device_parameter", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_calibration_relevant", sa.Boolean(), nullable=True)
        )
    update_query = "update device_parameter set is_calibration_relevant = false where is_calibration_relevant is null"
    connection = op.get_bind()
    connection.execute(update_query)
    # ### end Alembic commands ###


def downgrade():
    """Undo the database structure change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device_parameter", schema=None) as batch_op:
        batch_op.drop_column("is_calibration_relevant")
    # ### end Alembic commands ###
