# SPDX-FileCopyrightText: 2026
# - Nils Brinckmann <nils.brinckmann@gfz-potsdam.de>
# - Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences (GFZ, https://www.gfz-potsdam.de)
# - Helmholtz Centre for Environmental Research GmbH - UFZ (UFZ, https://www.ufz.de)
#
# SPDX-License-Identifier: EUPL-1.2

"""Add separate fields for eu and us eccn.

Revision ID: c5f2c6fc971e
Revises: 9aa14bd36aca
Create Date: 2026-04-13 13:23:43.611097

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c5f2c6fc971e"
down_revision = "9aa14bd36aca"
branch_labels = None
depends_on = None


def upgrade():
    """Add columns for different eccns."""
    with op.batch_alter_table("export_control", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "eu_export_control_classification_number",
                sa.String(length=256),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "us_export_control_classification_number",
                sa.String(length=256),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("us_re_export_control", sa.Boolean, nullable=True)
        )
    connection = op.get_bind()
    update_eu_eccn_query = """
    update export_control
    set eu_export_control_classification_number = export_control_classification_number
    where export_control_classification_number not ilike '(us) %'
    """
    connection.execute(sa.text(update_eu_eccn_query))
    update_us_eccn_query = """
    update export_control
    set us_export_control_classification_number = substring(export_control_classification_number, 6)
    where export_control_classification_number ilike '(us) %'
    """
    connection.execute(sa.text(update_us_eccn_query))
    update_us_re_export_control = """
    update export_control
    set us_re_export_control = true
    where export_control_classification_number ilike '(us) %'
    or additional_information ilike '%us re-export control%'
    """
    connection.execute(sa.text(update_us_re_export_control))


def downgrade():
    """Remove the columns for the separate eccn numbers."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("export_control", schema=None) as batch_op:
        batch_op.drop_column("us_export_control_classification_number")
        batch_op.drop_column("eu_export_control_classification_number")
        batch_op.drop_column("us_re_export_control")
    # ### end Alembic commands ###
