from safrs import SAFRSAPI

from project.api.models import *


def create_api(app, HOST="localhost", PORT=5000, API_PREFIX=""):
    api = SAFRSAPI(app, host=HOST, port=PORT, prefix=API_PREFIX)
    api.expose_object(DeviceCalibrationAction)
    api.expose_object(DevicePropertyCalibration)
    api.expose_object(DeviceCalibrationAttachment)
    api.expose_object(Configuration)
    api.expose_object(ConfigurationAttachment)
    api.expose_object(ConfigurationDevice)
    api.expose_object(ConfigurationStaticLocationBeginAction)
    api.expose_object(ConfigurationDynamicLocationEndAction)
    api.expose_object(ConfigurationDynamicLocationBeginAction)
    api.expose_object(ConfigurationStaticLocationEndAction)
    api.expose_object(ConfigurationPlatform)
    api.expose_object(Contact)
    api.expose_object(CustomField)
    api.expose_object(Device)
    api.expose_object(DeviceAttachment)
    api.expose_object(DeviceProperty)
    api.expose_object(Event)
    api.expose_object(GenericPlatformActionAttachment)
    api.expose_object(GenericConfigurationActionAttachment)
    api.expose_object(GenericDeviceActionAttachment)
    api.expose_object(GenericPlatformAction)
    api.expose_object(GenericDeviceAction)
    api.expose_object(GenericConfigurationAction)
    api.expose_object(PlatformMountAction)
    api.expose_object(DeviceMountAction)
    api.expose_object(Platform)
    api.expose_object(PlatformAttachment)
    api.expose_object(PlatformSoftwareUpdateActionAttachment)
    api.expose_object(DeviceSoftwareUpdateActionAttachment)
    api.expose_object(DeviceSoftwareUpdateAction)
    api.expose_object(PlatformSoftwareUpdateAction)
    api.expose_object(DeviceUnmountAction)
    api.expose_object(PlatformUnmountAction)
