# SPDX-FileCopyrightText: 2020 - 2024
# - Nils Brinckmann <nils.brinckmann@gfz-potsdam.de>
# - Marc Hanisch <marc.hanisch@gfz-potsdam.de>
# - Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences (GFZ, https://www.gfz-potsdam.de)
#
# SPDX-License-Identifier: EUPL-1.2

version : '3'

services:
  frontend:
    image: registry.hzdr.de/hub-terra/sms/frontend:ufz-latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
